name: Run Tests Client
on: 
  pull_request:
    branches:
      - '*'
    paths:
      - 'client/**'
  workflow_dispatch:
    branches:
      - '*'
    paths:
      - 'client/**'
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup and run tests
      working-directory: ./client
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        yarn
        yarn run lint 
        yarn run test
