name: Run Tests Server
on: 
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup and run tests
      working-directory: ./server
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        yarn
        yarn run test
