name: Run Tests Server
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup and run tests
      working-directory: ./server
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        yarn
        yarn run test
